export const UPDATE_PHOTOS = 'UPDATE_PHOTOS';
export const UPDATE_FILTER_QUERY = 'UPDATE_FILTER_QUERY';
export const START_LOADING = 'START_LOADING';
export const FINISH_LOADING = 'FINISH_LOADING';
export const FINISH_LOADING_INFINITE_SCROLL = 'FINISH_LOADING_INFINITE_SCROLL';
export const INCREMENT_PAGE = 'INCREMENT_PAGE';